##### Metadata and configuration for the website #####

title: Arielle's Thirtieth Birthday Party
description: Arielle's Thirtieth Birthday Party
subTitle: Picnic in the park

dates:
  rsvp: 2022-12-10T00:00:00+10:00
  party: 2023-01-21T13:00:00+10:00

blurb:
  title: Blurb
  paragraphs:
    - Paragraph One
    - Paragraph Two

rsvp:
  open:
    icon: event_available
    label: RSVP to the Party
  modal:
    title: RSVP
    closeButton:
      icon: close
      label: Close
    forms:
      name:
        name:
          label: Name
          placeholder: Please enter you're name
        nextButton:
          icon: arrow_forward_ios
          label: Next
      isAttending:
        paragraphs:
          - Are you attending?
        yesButton:
          label: Yes
          icon: arrow_forward_ios
        noButton:
          label: No
          icon: close
      notAttending:
        paragraphs:
          - That's too bad!
          - Please hit submit to let us know
        submitButton:
          icon: send
          label: Submit
        closeButton:
          icon: arrow_back
          label: Close
      attending:
        paragraphs:
          - Woohoo!
          - Please fill out the form to let us know!
        inputs:
          name:
            label: Name
            placeholder: Name
          dogs:
            label: "# Dogs"
            options:
              - None
              - 1
              - 2
              - 3
          kids:
            label: "# Kids"
            options:
              - None
              - 1
              - 2
              - 3
          notes:
            label: Notes
            placeholder: Notes
        statement:
          paragraphs:
            - All actions will be taken to make the event as environmentally friendly as possible.
            - All food served will be 100% plant based.
        submitButton:
          icon: send
          label: Submit
      submitted:
        thankYou: Thank you!
        paragraphs:
          - We look forward to seeing you

information:
  expandText:
    full: Find out more
    small: More
  sections:
    - name: Where
      label: Centennial Parklands
      paragraphs:
        - The party will take place at Centennial Park. The exact location can be seen below in Google Maps.
    - name: When
      label: Saturday, January 21, 2023
      paragraphs:
        - Information about the date of the party.
    - name: Time
      label: 2pm
      paragraphs:
        - Information about the time (or something else) and the afterparty.

countdown:
  text: Countdown to party

footer:
  createdBy:
    text: Created by Oliver Plummer
    website:
      text: olyop.com
      url: https://olyop.com
  sourceCode:
    text: Source Code
    url: https://github.com/olyop/ariellesbirthday
