title: Arielle's Thirtieth Birthday Party
description: Arielle's Thirtieth Birthday Party
subTitle: Picnic in the park

dates:
  rsvp: 2022-12-10T00:00:00+10:00
  party: 2023-01-21T13:00:00+10:00

blurb:
  title: Blurb
  paragraphs:
    - Paragraph One
    - Paragraph Two

rsvp:
  open:
    icon: event_available
    label: RSVP to the Party
  modal:
    title: RSVP
    closeButton:
      icon: close
      label: Close
    forms:
      name:
        inputs:
          name:
            label: Name
            placeholder: Please enter you're name
        nextButton:
          icon: arrow_forward_ios
          label: Next
      isAttending:
        paragraphs:
          - Are you attending?
        yesButton:
          icon: arrow_forward_ios
          label: Yes
        noButton:
          icon: close
          label: No
      notAttending:
        paragraphs:
          - That's too bad!
          - Hit submit to let us know
        submitButton:
          icon: send
          label: Submit
        closeButton:
          icon: arrow_back
          label: Close
      attending:
        paragraphs:
          - Woohoo!
          - Please fill out the form to let us know!
        inputs:
          name:
            label: Name
            placeholder: Name
        submitButton:
          icon: send
          label: Submit

information:
  expandText:
    full: Find out more
    small: More
  sections:
    - name: Where
      label: Centennial Parklands
      paragraphs:
        - The party will take place at Centennial Park. The exact location can be seen below in Google Maps.
    - name: When
      label: Saturday, January 21, 2023
      paragraphs:
        - Information about the date of the party.
    - name: Time
      label: 2pm
      paragraphs:
        - Information about the time (or something else)

countdown:
  text: Countdown to party

footer:
  createdBy:
    text: Created by Oliver Plummer
    website:
      text: olyop.com
      url: https://olyop.com
  sourceCode:
    text: Source Code
    url: https://github.com/olyop/ariellesbirthday
