dates:
  rsvp: 2022-12-10T00:00:00+10:00
  party: 2023-01-21T13:00:00+10:00

title: Arielle's Thirtieth<br/> Birthday Party
pageTitle: Arielle's Thirtieth Birthday Party
subTitle: Picnic in the park

rsvp:
  button:
    icon: event_available
    text: RSVP to the party

information:
  expandText:
    full: Find out more
    small: More
  sections:
    - name: Where
      label: Centennial Parklands
      paragraphs:
        - The party will take place at Centennial Park. The exact location can be seen below in Google Maps.
    - name: When
      label: Saturday, January 21, 2023
      paragraphs:
        - Information about the date of the party.
    - name: Time
      label: 2pm
      paragraphs:
        - Information about the time (or something else)

footer:
  createdBy:
    text: Created by Oliver Plummer
    link:
      url: https://olyop.com
      text: olyop.com
